### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by Jiacheng188** [ddcanedo/synthesis_tool#1]
i follow the guide in readme file, but i meet an error 
![image](https://user-images.githubusercontent.com/78731659/158937630-190a7aea-2afd-465e-88c6-14909154bd5f.png)
could you please give some advice?
Thank you for your kind assistance

**Comment by ddcanedo** [comment]
Hello,

It seems you managed to run it for several images. Could you please check if the images and their labels are being stored in test_tool/blended_floor_images//images/train/ and  test_tool/blended_floor_images//labels/train/ respectively?
If not, create the missing folders and run it again.

The program seems to be crashing at a certain image. Could you please remove the image 129 from test_tool/floors/patterns and run it again? It could be happening because OpenCV is not loading that image properly. 

Thanks for your feedback!

**Comment by Jiacheng188** [comment]
So kind of you! Thanks for your kind assistance.
1.create the folders,and
2.remove the image129
I soved the problem! Thanks again for your help!
