### ISSUE TITLE
Questions about functionality

### ISSUE THREAD

**Issue by Jiacheng188** [ddcanedo/synthesis_tool#2]
Hello..It's me again.
This time I have two questions.

- When I changed the parameters in  launch/image_blender_params.yaml ,such as **max_num_dirts**,**min_num_dirts**, both to zero, the progrem broke down again.(Now I am sorry that I am not able to show the screenshot because I can't contact to my server) 
- I found the dirt and liquids in the synthesized are really small compared to the whole background. Is there any choice for me to adjust the size of the waste?

I am not good at c++, so It's pretty difficult for me to watch the source code to solve the problems. Could you please help me?
Thanks again!

**Comment by ddcanedo** [comment]
Hello,

I apologize for the late response.


1. The tool is structured in a way such that the maximum and minimum parameters cannot be equal. Therefore, let's say that you do not want solid dirt samples in your dataset. You have 2 ways of achieving that: 

- Either you comment the line 132 of image_blend.cpp: blendImageDirt(...); 
- Or you change the min_num_dirts to 0 and max_num_dirts to 1 in the image_blender_params.yaml, since the range of the number of dirt samples is [min, max[.


2. You can only adjust the dirt size by modifying the code. In the function blendImagePatch(), the variable _alpha_ controls the dirt size. The tool is basically randomizing a alpha value between a minimum and a maximum. For instance, in this line:

alpha = (5 + ( rand() % ( 7 - 5 + 1 ) ))*0.01;

The variable alpha will vary between 0.05 and 0.07, the bigger the value, the bigger the dirt size. If you want to increase the dirt size you can change this range or even give alpha a constant value. I give you 2 examples that will increase the dirt size:

alpha = (10 + ( rand() % ( 30 - 10 + 1 ) ))*0.01;    // alpha will vary between 0.1 and 0.3
or
alpha = 0.3;  // alpha is 0.3

Do not increase the alpha value too much. I think over 0.8 the tool is likely to crash. I did not have time to fix that problem yet.

After any modification you make to the code, do not forget to compile the tool again using "make" before running it again.


Thank you & Kind regards,
Daniel

**Comment by Jiacheng188** [comment]
Thank you very much for your help! It will save me much time.
: D
